## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [3]:
import numpy as np
a = np.loadtxt("C:\\Users\\sankl\\OneDrive\\Документы\\minutes_n_ingredients.csv", delimiter = ",", dtype = np.int32, skiprows = 1)
a[0:5]

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       [ 67660,      5,      6],
       [157911,     60,     14]])

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [4]:
ma2 = np.max(a[:,1:2])
ma3 = np.max(a[:,2])
print(f"макимальное значение во втором столбце {ma2}, в третьем столбце {ma3}")
mi2 = np.min(a[:,1:2])
mi3 = np.min(a[:,2])
print(f"минимальное значение во втором столбце {mi2}, в третьем столбце {mi3}")
me2 = np.mean(a[:,1:2])
me3 = np.mean(a[:,2])
print(f"среднее значение во втором столбце {me2}, в третьем столбце {me3}")
med2 = np.median(a[:, 1:2])
med3 = np.median(a[:, 2])
print(f"значение медианы во втором столбце {med2}, в третьем столбце {med3}")

макимальное значение во втором столбце 2147483647, в третьем столбце 39
минимальное значение во втором столбце 0, в третьем столбце 1
среднее значение во втором столбце 21601.00169, в третьем столбце 9.05528
значение медианы во втором столбце 40.0, в третьем столбце 9.0


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [5]:
q = np.quantile(a[:,1], 0.75)
new_a1 =  a[a[:,1] <= q]
new_a1


array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       ...,
       [ 43407,     35,      7],
       [498432,     65,     15],
       [370915,      5,      4]])

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [6]:
print(list(a[:,1]).count(0))
a[a == 0] = 1

479


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [7]:
len(np.unique(a[:,0]))

100000

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [8]:
print(len(np.unique(a[:,2])))
print(np.unique(a[:,2]))

37
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39]


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [9]:
a2 = a[a[:,2] <= 5]
print(a2)

[[446597     15      5]
 [204134      5      3]
 [ 25623      6      4]
 ...
 [ 52088     60      5]
 [128811     15      4]
 [370915      5      4]]


8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [10]:
a3 = a[:,2] / a[:,1]
print(a3)
print(np.max(a3))

[0.26666667 0.28       0.6        ... 0.23076923 0.8        0.1       ]
24.0


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [11]:
a4 = a[np.argsort(a[:,1])][-100:,2]
print(np.mean(a4))

6.61


10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [12]:
print(a[np.random.randint(a.shape[0], size=10)])

[[193710     45     11]
 [ 98483     75     17]
 [142961     25      7]
 [ 40267     45      5]
 [285509     20      2]
 [ 50784    490      7]
 [345490     30     18]
 [516959     35     13]
 [219353     90     17]
 [357716    150     10]]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [13]:
a5 = (a[a[:,2] < np.mean(a[:,2])].shape[0])/a.shape[0]
print(a5*100)

58.802


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [14]:
a_q = (a[:,1] <= 20) & (a[:,2] <= 5)
a6 = np.hstack((a, a_q[:,np.newaxis]))
print(a6)

[[127244     60     16      0]
 [ 23891     25      7      0]
 [ 94746     10      6      0]
 ...
 [498432     65     15      0]
 [370915      5      4      1]
 [ 81993    140     14      0]]


13. Выведите процент "простых" рецептов в датасете

In [15]:
a7 = a6[a6[:,3] == 1]
print((a7.shape[0]/a.shape[0]) *100)

9.552


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [36]:
amal = a[a[:,1] < 10]
asr = a[(a[:,1] >= 10) & (a[:,1] < 20)]
amax = a[a[:,1] >= 20]
crit = min(amal.shape[0], asr.shape[0], amax.shape[0])
A = np.arange(crit*3*4).reshape(3, crit, 4)  
A[0,:,0] = 0
A[1,:,0] = 1
A[2,:,0] = 2
A[0][:,1:] = amal[:crit,:]
A[1][:,1:] = asr[:crit,:]
A[2][:,1:] = amax[:crit,:]
print(amal.shape, asr.shape, amax.shape)
print(A)

(7588, 3) (12661, 3) (79751, 3)
[[[     0  67660      5      6]
  [     0 366174      7      9]
  [     0 204134      5      3]
  ...
  [     0 420725      5      3]
  [     0   4747      1      9]
  [     0 370915      5      4]]

 [[     1  94746     10      6]
  [     1  33941     18      9]
  [     1 446597     15      5]
  ...
  [     1   9831     15      7]
  [     1 335859     12     14]
  [     1 256812     10      3]]

 [[     2 127244     60     16]
  [     2  23891     25      7]
  [     2 157911     60     14]
  ...
  [     2 168901     25      7]
  [     2 392339     35     13]
  [     2 206732     45     10]]]
